【API設計】authサービス
YungTatyu/transcendence pull request #29
Opened 2024-12-13 02:15 UTC by YungTatyu

# 対応内容
/authのapi設計
## 確認して欲しいファイル
auth.yaml
## 確認の仕方
1. auth.yamlの中身をコピー
2. [swagger](https://editor.swagger.io/)にアクセスし、コピーしたものを貼り付ける

## 注意事項
api設計全体の方針としてテーブルのカラムごとにエンドポイントを分けています。
例えば、emailの更新とpasswordの更新は違うエンドポイント
理由として、
- バックエンドのロジックが複雑になる
emailのバリデーションとpassword更新のロジック（現在のパスワードが正しいかチェック）など複数のロジックが混在する
- カラムによっては、responseもしくはrequestBodyのデータ形式がjsonでない方がいい場合があり、エンドポイント統一が難しい場合がある
例えば、アバター画像をresponseで返す場合は、jsonでない方が良い
- 現状の画面設計では、複数のカラムを同時に更新させなくしている

分からない点は何でもコメントに残して質問してください。

2024-12-14 09:02 UTC, rikeda-cloud requested changes
コメントいくつか残したので確認よろしくお願います。

認証サーバ以外のAPIサーバでJWTを検証するための公開鍵はどのように取得する想定ですか？
あらかじめ、各APIサーバに公開鍵をインストールしておく場合は問題ないですが、
認証サーバがJWT検証用の公開鍵を配信する場合は、公開鍵配信用のエンドポイントが必要そうです。

2024-12-15 02:15 UTC, YungTatyu commented on docs/auth.yaml
> +                    example: "Invalid email format."
409エラーのほうがいいですね。
追加します。

2024-12-15 02:17 UTC, YungTatyu commented on docs/auth.yaml
> +                    example: "Invalid email format."
409エラーで対応します。

2024-12-15 02:24 UTC, YungTatyu commented on docs/auth.yaml
> +                    description: "refreshトークン"
引用ですが、大もかな流れは以下です。
https://qiita.com/otoiku/items/a8dfddebd56b1177d6df
1. クライアントはユーザIDとパスワードをサーバに送る。
2. サーバが認証を行い、OKだったらアクセストークン***＆リフレッシュトークン***を発行しクライアントに送る。
3. クライアントはリクエストのたびにアクセストークンも一緒に送る。
4. サーバがアクセストークンを復号して認証・認可する。
5. アクセストークンの有効期限が切れサーバがエラーを返した場合：クライアントはリフレッシュトークンをサーバに送ってアクセストークンの再発行を行う。

2024-12-15 04:40 UTC, rikeda-cloud commented on docs/auth.yaml
> +                    description: "refreshトークン"
JWTにユーザーIDやトークンの有効期限、発行者などの情報ををもたせるとアクセストークンとして機能する
というような認識であっていますか？

アクセストークンとリフレッシュトークンはJWTの形式で保持するという認識であっていますか？

2024-12-15 07:43 UTC, YungTatyu commented on docs/auth.yaml
> +                    description: "refreshトークン"
```
アクセストークンはJWT形式で作成されるのが一般的です。
リフレッシュトークンもJWT形式を使う場合がありますが、よりセキュリティを重視して単なるランダムなトークン文字列を使用することもあります。
```
アクセストークンがjwt形式になっているという理解です。
なので、以下の用になる想定です。
JWT = アクセストークン
リフレッシュトークン = 単なるランダムな文字列

2024-12-15 07:55 UTC, rikeda-cloud commented on docs/auth.yaml
> +                    description: "refreshトークン"
リフレッシュトークンはどのような形で保持されますか？
また、ブラウザのストレージ内で保管されるとして、サーバー側でリフレッシュトークンのデータを保存する必要などはありますか？

2024-12-15 08:10 UTC, YungTatyu commented on docs/auth.yaml
> +                    description: "refreshトークン"
自分で実装した時はlocal storageに保存していましたが、
チャットgptは以下のような回答をしました。
以下はセキュリティを考慮してるみたいです。
アクセストークン: メモリまたはセッションストレージで保存し、APIリクエストにヘッダーで付与する。
リフレッシュトークン: HTTP-Only Cookieで保存し、トークン再発行エンドポイントで使用する。

cookieに保存するのが安全ぽい？
https://zenn.dev/nameless_sn/articles/the_best_practice_of_jwt

2024-12-15 09:01 UTC, rikeda-cloud commented on docs/auth.yaml
> +                    description: "refreshトークン"
リフレッシュトークンをJWTとして実装する場合
- JWTを検証し、JWT内の有効期限等を使用すればよいのでステートレス
- JWTが流出した際にJWTを無効化する手段がない
- 高いスケーラビリティが必要な場合やセキュリティ要件が適度な場合に有効的

リフレッシュトークンをランダム文字列として実装する場合
- 認証サーバのDBやメモリ上に有効期限とランダム文字列を保持し、DBのランダム文字列とリクエストボディのランダム文字列を比較するため、ステートフル
- リフレッシュトークンの無効化が容易
- リフレッシュトークンの厳密な管理が必要である場合に効果的

JWTかつブラックリストを使用して実装する場合
- JWTによる実装のため手軽
- ブラックリストを利用することでJWTが流出した際の無効化が容易
- ブラックリストの情報をDBやメモリに保持する必要有り
- スケーラビリティとセキュリティのバランスを取りたい場合に効果的

ランダム文字列やブラックリストを使う場合はDB設計を少し修正します。
ランダム文字列・・・user_authテーブルにランダム文字列と有効期限カラムを追加
ブラックリスト・・・メモリ上にJWTのブラックリストを保持

どうしますか？

2024-12-15 11:26 UTC, YungTatyu commented on docs/auth.yaml
> +                    description: "refreshトークン"
drfでjwtを実装していた時は、ブラックリストを使用していました。
ブラックリストの用途としては、ログアウトしたときに、jwtをブラックリストに追加するなどです。

drfではデータベースを意識せずに使用していました
おそらくブラックリストはメモリ上ではなくて、勝手にDBで管理してくれていた思います
https://django-rest-framework-simplejwt.readthedocs.io/en/latest/blacklist_app.html

2024-12-15 11:47 UTC, YungTatyu commented on docs/auth.yaml
> +                    description: "refreshトークン"
今調べてみると、refreshトークンもjwtかもしれないです。
jwtのidでブラックリストを管理しているっぽいです

2024-12-15 11:50 UTC, YungTatyu commented on docs/auth.yaml
> +                    description: "refreshトークン"
refreshトークンもjwt形式でした。
ブラックリストでは、jtiを管理しているみたいです。
```js
{
  "token_type": "refresh",
  "exp": 1650295108,
  "iat": 1650208708,
  "jti": "aa67d517900f4112a6951413f5d84984",
  "user_id": 1
}
```

2024-12-16 04:11 UTC, kealoke approved these changes

2024-12-16 04:12 UTC, YungTatyu commented
> コメントいくつか残したので確認よろしくお願います。
> 
> 認証サーバ以外のAPIサーバでJWTを検証するための公開鍵はどのように取得する想定ですか？
> あらかじめ、各APIサーバに公開鍵をインストールしておく場合は問題ないですが、
> 認証サーバがJWT検証用の公開鍵を配信する場合は、公開鍵配信用のエンドポイントが必要そうです。

公開鍵はセキュリティモジュールのVaultで管理しますよね？
公開鍵をどう取得するかは考えれていなかったです。
以下のような流れですかね？

以下は、公開鍵取得からJWT検証までのフロー全体の概要です：

Vaultに公開鍵を保存
管理者や認証サービスがVaultに公開鍵を事前登録します。

1. APIサーバがVaultから公開鍵を取得

2. APIサーバはVaultのAPIを使用して公開鍵を取得。
必要に応じてローカルキャッシュに保存。
クライアントからJWTを受け取る
APIサーバはクライアントから送られてきたJWTを受け取ります。

3. 公開鍵でJWTを検証
Vaultから取得した公開鍵を使用してJWTを検証します。

2024-12-16 08:15 UTC, rikeda-cloud commented on docs/auth.yaml
> +                    description: "refreshトークン"
refreshトークンもJWTで管理しましょう

2024-12-16 08:20 UTC, rikeda-cloud commented
Vaultというのは聞いたことがなかったです。
Vaultサーバというのを別途立ち上げるという形ですか？
自分の想定では
```
1. 認証サーバ内に公開鍵を生成
2. 認証サーバの公開鍵を配信するエンドポイントを用意
3. 各APIサーバがエンドポイントを叩き、公開鍵を取得
```
の流れでした。
認証サーバをまるまるVaultサーバに読み替える感じですか？

2024-12-16 08:27 UTC, rikeda-cloud commented
> Vaultというのは聞いたことがなかったです。 Vaultサーバというのを別途立ち上げるという形ですか？ 自分の想定では
> 
> ```
> 1. 認証サーバ内に公開鍵を生成
> 2. 認証サーバの公開鍵を配信するエンドポイントを用意
> 3. 各APIサーバがエンドポイントを叩き、公開鍵を取得
> ```
> 
> の流れでした。 認証サーバをまるまるVaultサーバに読み替える感じですか？

セキュリティモジュールのWAFにくっついていたやつなんですね...
WAFに目が行き過ぎて見落としていました。すみません。

公開鍵はVaultサーバで配信し、各APIサーバがVaultサーバを叩いて公開鍵を取得する感じですね。

2025-01-10 07:09 UTC, rikeda-cloud approved these changes
LGTM！

2025-01-10 10:39 UTC, Kazuki-Asaka approved these changes
確認しました。

2025-01-10 16:42 UTC, kealoke approved these changes

2025-01-13 03:13 UTC, merged